# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

SCRATCH="/mnt/scratch2/users/40146600"
alias scratch="cd $SCRATCH"
PROJECT="/mnt/autofs/mcclayrds-projects/ad00069"
alias project="cd $PROJECT"

alias queue="squeue -u 40146600"
alias report="sacct --format=JobID,JobName,Partition,AllocCPUs,NNodes,ReqMem,State,MaxRSS,MaxVMSize,Elapsed,Submit,Start,End -j"

alias of12="module load apps/openfoam/12/gcc-14.1.0+openmpi-5.0.3+cmake-3.29.2+qt-5.15.11"
alias of2406="module load apps/openfoamplus/24.06/gcc-14.1.0+openmpi-5.0.3+mgridgen-1.0+qt-5.15.11"
alias of8="module load apps/openfoam/8/gcc-8.5.0+openmpi-4.1.6+cmake-3.29.2+qt-5.15.11"
alias gp="module load apps/gnuplot/5.0.2/gcc-4.8.5"

alias mpl="conda activate mpl"
alias pvserverjob="rm ./log.pvserver; sbatch ~/scripts/pvserver.sh"
alias pvbatch="rm ./log.pvbatch; sbatch ~/scripts/pvbatch.sh"

csv()
{
    column -s, -t < $1 | less -#2 -N -S
}

sowfa24x()
{
    module load mpi/openmpi/1.10.1/gcc-4.8.5
    module load apps/cmake/3.5.2/gcc-4.8.5

    if [ -z "$FOAM_INST_DIR" ]; then
        echo "Nothing to unset..."
    else
        echo "Unsetting OpenFOAM environment variables..."
        . $FOAM_INST_DIR/OpenFOAM-$OPENFOAM_VERSION/etc/config/unset.sh 2>&1 \
                                                                    > /dev/null
        export FOAM_INST_DIR=$HOME/OpenFOAM
    fi

    export FOAM_INST_DIR=$HOME/OpenFOAM
    export OPENFOAM_VERSION=2.4.x
    export OPENFOAM_NAME=OpenFOAM-$OPENFOAM_VERSION

    foamDotFile=$FOAM_INST_DIR/$OPENFOAM_NAME/etc/bashrc

    if [ -f $foamDotFile ] ; then
        echo "Sourcing $foamDotFile..."
        source $foamDotFile
    fi

    export WM_NCOMPPROCS=24
    export WM_COLOURS="white blue green cyan red magenta yellow"

    export SOWFA_DIR=$FOAM_INST_DIR/SOWFA-2.4.x
    export LD_LIBRARY_PATH=$SOWFA_DIR/lib/$WM_OPTIONS:$LD_LIBRARY_PATH
    export PATH=$SOWFA_DIR/applications/bin/$WM_OPTIONS:$PATH
}

of2412()
{
    module load openmpi
    source ~/OpenFOAM/OpenFOAM-v2412/etc/bashrc
}

tfoam()
{
    module load libs/armadillo
    module load apps/openfoamplus/24.06/gcc-14.1.0+openmpi-5.0.3+mgridgen-1.0+qt-5.15.11
    
    # Manually add path to gcc-14.1.0
    export PATH=/opt/gridware/depots/54e7fb3c/el8/pkg/compilers/gcc/14.1.0/bin/:$PATH

    # Manually add FOAM_USER paths
    export FOAM_USER_LIBBIN=/mnt/scratch2/users/$USER/OpenFOAM/$USER-v$FOAM_API/platforms/$WM_OPTIONS/lib
    export LD_LIBRARY_PATH=$FOAM_USER_LIBBIN:$LD_LIBRARY_PATH

    export FOAM_USER_APPBIN=/mnt/scratch2/users/$USER/OpenFOAM/$USER-v$FOAM_API/platforms/$WM_OPTIONS/bin
    export PATH=$FOAM_USER_APPBIN:$PATH
}

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba shell init' !!
export MAMBA_EXE='/users/40146600/miniforge3/bin/mamba';
export MAMBA_ROOT_PREFIX='/users/40146600/miniforge3';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias mamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<
